theme: jekyll-theme-dinky

title: Francois R Foerster, PhD

description: Cognitive neuroscientist

avatar: ![ProfilPicture](/francoisrfoerster.github.io/docs/assets/francois.jpg)


# Includes an icon in the footer for each username you enter
footer-links:
  email: francoisfoerster@gmail.com
  googlescholar: https://scholar.google.co.uk/citations?user=oPWQIcoAAAAJ&hl=en
  osf: https://osf.io/8q6g2/
  linkedin: https://www.linkedin.com/in/francois-foerster-neuro/
  github: https://github.com/FrancoisFoerster
  
